DocumentationTitleEn: Notification Center Pro
DocumentationTitleDe: Notification Center Pro
extensionPermalink: https://extensions.terminal42.ch/p/nc-pro
extensionIcon: extension.svg
editURL: https://github.com/terminal42/extensions-docs/edit/main/docs/notification-center-pro/
