themeVariant: 'terminal42'
disableSearch: false
disableLanguageSwitch: false
documentation_label: Extension
showVisitedLinks: true
disableInlineCopyToClipBoard: true
#disableAssetsBusting: true
disableLandingPageButton: true
extensionPermalink: ''
DocumentationTitleEn: Make sure to configure the parameter "DocumentationTitleEn" in this extension book.
DocumentationTitleDe: Stelle sicher, dass der Parameter "DocumentationTitleEn" in diesem Erweiterungsbuch konfiguriert ist.