themeVariant: 'contao'
disableSearch: false
disableLanguageSwitch: true
documentation_label: Documentation
showVisitedLinks: true
disableInlineCopyToClipBoard: true
#disableAssetsBusting: true
disableLandingPageButton: true
extensionPermalink: https://extensions.terminal42.ch