name: Build and deploy

on:
    push:
        branches:
            - main
    workflow_dispatch: ~

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.120.4'

            - name: Build all books
              run: make build

            - name: Deploy
              uses: appleboy/scp-action@master
              with:
                  host: terminal42.ch
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  port: ${{ secrets.DEPLOY_PORT }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  source: 'build'
                  target: ${{ secrets.DEPLOY_TARGET_PATH }}
                  rm: true
                  strip_components: 1